sudo: required
services:
  - docker

before_install:
  - docker build -t murugacharan/docker-react -f Dockerfile.dev .

script:
  - docker run murugacharan/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-muruga"
  env: "DockerReactMuruga-env"
  bucket_name: "elasticbeanstalk-us-east-1-220142308442"
  bucket_path: "docker-react-muruga"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

